[package]
name = "fmitestbed"
version = "0.0.1"
authors = ["Antti Peltonen <antti.peltonen@iki.fi>"]

[dependencies]
regex = "1.0.2"
reqwest = "0.8.7"
url = "1.7.1"
chrono = "0.4.5"
image = "0.19.0"
gio = "0.4.1"
gdk-pixbuf = "0.4.0"

[dependencies.gtk]
version = "0.4.1"
features = ["v3_10"]
